spring:
  application:
    name: hrm
  datasource:
    url: jdbc:postgresql://localhost:5432/hrm
    username: postgres
    password: coffee1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect